version: '3'
services:
  web:
    build: ./
    image: nginxxxxxxxxxxxx
    ports:
      - 55555:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
